# Generated by Django 4.1.2 on 2022-10-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('item_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('date_created', models.DateField()),
                ('tag', models.CharField(max_length=64)),
                ('picture', models.CharField(max_length=64)),
            ],
        ),
    ]
